version: '3.8'
services:
    web:
       build: app
       command: python main.py
       ports:
           - "8000:8000"
    nginx:
        image: nginx:latest
        restart: always
        expose:
          - 8080
        ports:
          - "80:8080"
        volumes:
            - ./static:/var/www/static
            - ./nginx/:/etc/nginx/conf.d
        depends_on:
            - web