# Generated by Django 4.2.10 on 2025-05-03 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Directory", "0001_initial"),
        ("Payment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcategory",
            name="category",
        ),
        migrations.AlterField(
            model_name="payment",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Directory.category",
                verbose_name="Категория ДДС",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Directory.type",
                verbose_name="Тип ДДС",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Directory.status",
                verbose_name="Статус ДДС",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Directory.subcategory",
                verbose_name="подкатегория ДДС",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Status",
        ),
        migrations.DeleteModel(
            name="Subcategory",
        ),
        migrations.DeleteModel(
            name="Type",
        ),
    ]
